---
- hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: Install yum packages
      yum:
        name: '{{ item }}'
        state: present
        update_cache: True
      with_items:
        - epel-release
        - python3
        - ntp
        - git

    