---
- hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: Install yum packages
      yum:
        name: ['epel-release','python3','git','ansible-core']
        state: present
        update_cache: True
    